import type { ListClientsQuery } from '../types/client'

const appScope = ['afriserve'] as const

export type QueryParams = Record<string, unknown>

export const queryKeys = {
  auth: {
    all: [...appScope, 'auth'] as const,
    me: () => [...queryKeys.auth.all, 'me'] as const,
  },
  clients: {
    all: [...appScope, 'clients'] as const,
    lists: () => [...queryKeys.clients.all, 'list'] as const,
    list: (query: ListClientsQuery) => [...queryKeys.clients.lists(), query] as const,
    details: () => [...queryKeys.clients.all, 'detail'] as const,
    detail: (clientId: number) => [...queryKeys.clients.details(), clientId] as const,
    onboardingStatuses: () => [...queryKeys.clients.all, 'onboarding'] as const,
    onboardingStatus: (clientId: number) => [...queryKeys.clients.onboardingStatuses(), clientId] as const,
    guarantorLists: () => [...queryKeys.clients.all, 'guarantors'] as const,
    guarantors: (clientId: number) => [...queryKeys.clients.guarantorLists(), clientId] as const,
    collateralLists: () => [...queryKeys.clients.all, 'collaterals'] as const,
    collaterals: (clientId: number) => [...queryKeys.clients.collateralLists(), clientId] as const,
    histories: () => [...queryKeys.clients.all, 'history'] as const,
    history: (clientId: number) => [...queryKeys.clients.histories(), clientId] as const,
    duplicates: () => [...queryKeys.clients.all, 'potential-duplicates'] as const,
    assignableOfficers: () => [...queryKeys.clients.all, 'assignable-officers'] as const,
  },
  loans: {
    all: [...appScope, 'loans'] as const,
    lists: () => [...queryKeys.loans.all, 'list'] as const,
    list: (params: QueryParams) => [...queryKeys.loans.lists(), params] as const,
    details: () => [...queryKeys.loans.all, 'detail'] as const,
    detail: (loanId: number) => [...queryKeys.loans.details(), loanId] as const,
    statements: () => [...queryKeys.loans.all, 'statement'] as const,
    statement: (loanId: number) => [...queryKeys.loans.statements(), loanId] as const,
    schedules: () => [...queryKeys.loans.all, 'schedule'] as const,
    schedule: (loanId: number) => [...queryKeys.loans.schedules(), loanId] as const,
    pendingApprovals: (params: QueryParams) => [...queryKeys.loans.all, 'pending-approval', params] as const,
    pendingApprovalLists: () => [...queryKeys.loans.all, 'pending-approval'] as const,
    collaterals: () => [...queryKeys.loans.all, 'collateral'] as const,
    collateral: (loanId: number) => [...queryKeys.loans.collaterals(), loanId] as const,
    guarantorLists: () => [...queryKeys.loans.all, 'guarantors'] as const,
    guarantors: (loanId: number) => [...queryKeys.loans.guarantorLists(), loanId] as const,
    approvalRequests: (params: QueryParams) => [...queryKeys.loans.all, 'approval-requests', params] as const,
    approvalRequestLists: () => [...queryKeys.loans.all, 'approval-requests'] as const,
    disbursementHistories: () => [...queryKeys.loans.all, 'disbursements'] as const,
    disbursements: (loanId: number) => [...queryKeys.loans.disbursementHistories(), loanId] as const,
    contractHistories: () => [...queryKeys.loans.all, 'contracts'] as const,
    contracts: (loanId: number) => [...queryKeys.loans.contractHistories(), loanId] as const,
    lifecycleEventLists: () => [...queryKeys.loans.all, 'lifecycle-events'] as const,
    lifecycleEvents: (loanId: number) => [...queryKeys.loans.lifecycleEventLists(), loanId] as const,
  },
  collections: {
    all: [...appScope, 'collections'] as const,
    summary: (params: QueryParams) => [...queryKeys.collections.all, 'summary', params] as const,
    summaries: () => [...queryKeys.collections.all, 'summary'] as const,
    overdue: (params: QueryParams) => [...queryKeys.collections.all, 'overdue', params] as const,
    overdues: () => [...queryKeys.collections.all, 'overdue'] as const,
    actions: (params: QueryParams) => [...queryKeys.collections.all, 'actions', params] as const,
    actionLists: () => [...queryKeys.collections.all, 'actions'] as const,
  },
  stakeholders: {
    all: [...appScope, 'stakeholders'] as const,
    monthlyPerformance: (params: QueryParams = {}) => [...queryKeys.stakeholders.all, 'monthly-performance', params] as const,
    cashFlowStatus: (params: QueryParams = {}) => [...queryKeys.stakeholders.all, 'cashflow-status', params] as const,
    glCashFlow: (params: QueryParams = {}) => [...queryKeys.stakeholders.all, 'gl-cashflow', params] as const,
    recentCapitalTransactions: (params: QueryParams = {}) => [...queryKeys.stakeholders.all, 'capital-transactions-recent', params] as const,
    pendingCapitalWithdrawals: (params: QueryParams = {}) => [...queryKeys.stakeholders.all, 'capital-pending-withdrawals', params] as const,
  },
  capital: {
    all: [...appScope, 'capital'] as const,
    transactions: () => [...queryKeys.capital.all, 'transactions'] as const,
    mine: (params: QueryParams = {}) => [...queryKeys.capital.transactions(), 'mine', params] as const,
    pending: (params: QueryParams = {}) => [...queryKeys.capital.transactions(), 'pending', params] as const,
    filtered: (params: QueryParams = {}) => [...queryKeys.capital.transactions(), 'filtered', params] as const,
    cashflowPosition: (params: QueryParams = {}) => [...queryKeys.capital.all, 'cashflow-position', params] as const,
  },
  reports: {
    all: [...appScope, 'reports'] as const,
    filterOptions: (params: QueryParams = {}) => [...queryKeys.reports.all, 'filter-options', params] as const,
    // Static named report keys (used by dedicated hooks)
    portfolio: (params: QueryParams) => [...queryKeys.reports.all, 'portfolio', params] as const,
    dailyCollections: (params: QueryParams) => [...queryKeys.reports.all, 'daily-collections', params] as const,
    boardSummary: (params: QueryParams) => [...queryKeys.reports.all, 'board-summary', params] as const,
    // Dynamic generated-report key (used by ReportsPage for any ad-hoc report path)
    generated: (reportId: string | null, params: QueryParams) =>
      [...queryKeys.reports.all, 'generated-report', reportId, JSON.stringify(params)] as const,
    // Per-endpoint invalidation helpers
    arrears: (params: QueryParams) => [...queryKeys.reports.all, 'arrears', params] as const,
    disbursements: (params: QueryParams) => [...queryKeys.reports.all, 'disbursements', params] as const,
    dues: (params: QueryParams) => [...queryKeys.reports.all, 'dues', params] as const,
    clients: (params: QueryParams) => [...queryKeys.reports.all, 'clients', params] as const,
    aging: (params: QueryParams) => [...queryKeys.reports.all, 'aging', params] as const,
    guarantors: (params: QueryParams) => [...queryKeys.reports.all, 'guarantors', params] as const,
    collections: (params: QueryParams) => [...queryKeys.reports.all, 'collections', params] as const,
    officerPerformance: (params: QueryParams) => [...queryKeys.reports.all, 'officer-performance', params] as const,
    incomeStatement: (params: QueryParams) => [...queryKeys.reports.all, 'income-statement', params] as const,
    writeOffs: (params: QueryParams) => [...queryKeys.reports.all, 'write-offs', params] as const,
    balanceSheet: (params: QueryParams) => [...queryKeys.reports.all, 'balance-sheet', params] as const,
    cashFlow: (params: QueryParams) => [...queryKeys.reports.all, 'cash-flow', params] as const,
    // Gap 8 advanced reports
    arrearsAging: (params: QueryParams) => [...queryKeys.reports.all, 'arrears-aging', params] as const,
    officerPerformanceV2: (params: QueryParams) => [...queryKeys.reports.all, 'officer-performance-v2', params] as const,
    branchPnl: (params: QueryParams) => [...queryKeys.reports.all, 'branch-pnl', params] as const,
    writeOffsPortfolio: (params: QueryParams) => [...queryKeys.reports.all, 'write-offs-portfolio', params] as const,
    capitalAdequacy: (params: QueryParams) => [...queryKeys.reports.all, 'capital-adequacy', params] as const,
    clientRetention: (params: QueryParams) => [...queryKeys.reports.all, 'client-retention', params] as const,
    // Performance / stakeholder reports
    performanceMonthly: (params: QueryParams) => [...queryKeys.reports.all, 'performance', 'monthly', params] as const,
    performanceCashflow: (params: QueryParams) => [...queryKeys.reports.all, 'performance', 'cashflow', params] as const,
    // GL sub-reports
    glAccounts: (params: QueryParams) => [...queryKeys.reports.all, 'gl', 'accounts', params] as const,
    glTrialBalance: (params: QueryParams) => [...queryKeys.reports.all, 'gl', 'trial-balance', params] as const,
    glIncomeStatement: (params: QueryParams) => [...queryKeys.reports.all, 'gl', 'income-statement', params] as const,
    glCashFlow: (params: QueryParams) => [...queryKeys.reports.all, 'gl', 'cash-flow', params] as const,
  },
  admin: {
    all: [...appScope, 'admin'] as const,
    users: (params: QueryParams) => [...queryKeys.admin.all, 'users', params] as const,
    usersLists: () => [...queryKeys.admin.all, 'users'] as const,
    usersSummary: () => [...queryKeys.admin.all, 'users-summary'] as const,
    userRoles: () => [...queryKeys.admin.all, 'users-roles'] as const,
    activeBranches: () => [...queryKeys.admin.all, 'active-branches'] as const,
    permissionCatalog: () => [...queryKeys.admin.all, 'permission-catalog'] as const,
    userPermissions: (userId: number) => [...queryKeys.admin.all, 'user-permissions', userId] as const,
    userSecurityState: (userId: number) => [...queryKeys.admin.all, 'user-security-state', userId] as const,
  },
}
