import type { ListClientsQuery } from '../types/client'

const appScope = ['afriserve'] as const

export type QueryParams = Record<string, unknown>

export const queryKeys = {
  auth: {
    all: [...appScope, 'auth'] as const,
    me: () => [...queryKeys.auth.all, 'me'] as const,
  },
  clients: {
    all: [...appScope, 'clients'] as const,
    lists: () => [...queryKeys.clients.all, 'list'] as const,
    list: (query: ListClientsQuery) => [...queryKeys.clients.lists(), query] as const,
    details: () => [...queryKeys.clients.all, 'detail'] as const,
    detail: (clientId: number) => [...queryKeys.clients.details(), clientId] as const,
    onboardingStatuses: () => [...queryKeys.clients.all, 'onboarding'] as const,
    onboardingStatus: (clientId: number) => [...queryKeys.clients.onboardingStatuses(), clientId] as const,
    guarantorLists: () => [...queryKeys.clients.all, 'guarantors'] as const,
    guarantors: (clientId: number) => [...queryKeys.clients.guarantorLists(), clientId] as const,
    collateralLists: () => [...queryKeys.clients.all, 'collaterals'] as const,
    collaterals: (clientId: number) => [...queryKeys.clients.collateralLists(), clientId] as const,
    histories: () => [...queryKeys.clients.all, 'history'] as const,
    history: (clientId: number) => [...queryKeys.clients.histories(), clientId] as const,
    duplicates: () => [...queryKeys.clients.all, 'potential-duplicates'] as const,
    assignableOfficers: () => [...queryKeys.clients.all, 'assignable-officers'] as const,
  },
  loans: {
    all: [...appScope, 'loans'] as const,
    lists: () => [...queryKeys.loans.all, 'list'] as const,
    list: (params: QueryParams) => [...queryKeys.loans.lists(), params] as const,
    details: () => [...queryKeys.loans.all, 'detail'] as const,
    detail: (loanId: number) => [...queryKeys.loans.details(), loanId] as const,
    statements: () => [...queryKeys.loans.all, 'statement'] as const,
    statement: (loanId: number) => [...queryKeys.loans.statements(), loanId] as const,
    schedules: () => [...queryKeys.loans.all, 'schedule'] as const,
    schedule: (loanId: number) => [...queryKeys.loans.schedules(), loanId] as const,
    pendingApprovals: (params: QueryParams) => [...queryKeys.loans.all, 'pending-approval', params] as const,
    pendingApprovalLists: () => [...queryKeys.loans.all, 'pending-approval'] as const,
    collaterals: () => [...queryKeys.loans.all, 'collateral'] as const,
    collateral: (loanId: number) => [...queryKeys.loans.collaterals(), loanId] as const,
    guarantorLists: () => [...queryKeys.loans.all, 'guarantors'] as const,
    guarantors: (loanId: number) => [...queryKeys.loans.guarantorLists(), loanId] as const,
    approvalRequests: (params: QueryParams) => [...queryKeys.loans.all, 'approval-requests', params] as const,
    approvalRequestLists: () => [...queryKeys.loans.all, 'approval-requests'] as const,
    disbursementHistories: () => [...queryKeys.loans.all, 'disbursements'] as const,
    disbursements: (loanId: number) => [...queryKeys.loans.disbursementHistories(), loanId] as const,
    contractHistories: () => [...queryKeys.loans.all, 'contracts'] as const,
    contracts: (loanId: number) => [...queryKeys.loans.contractHistories(), loanId] as const,
    lifecycleEventLists: () => [...queryKeys.loans.all, 'lifecycle-events'] as const,
    lifecycleEvents: (loanId: number) => [...queryKeys.loans.lifecycleEventLists(), loanId] as const,
  },
  collections: {
    all: [...appScope, 'collections'] as const,
    summary: (params: QueryParams) => [...queryKeys.collections.all, 'summary', params] as const,
    summaries: () => [...queryKeys.collections.all, 'summary'] as const,
    overdue: (params: QueryParams) => [...queryKeys.collections.all, 'overdue', params] as const,
    overdues: () => [...queryKeys.collections.all, 'overdue'] as const,
    actions: (params: QueryParams) => [...queryKeys.collections.all, 'actions', params] as const,
    actionLists: () => [...queryKeys.collections.all, 'actions'] as const,
  },
  reports: {
    all: [...appScope, 'reports'] as const,
    portfolio: (params: QueryParams) => [...queryKeys.reports.all, 'portfolio', params] as const,
    dailyCollections: (params: QueryParams) => [...queryKeys.reports.all, 'daily-collections', params] as const,
    boardSummary: (params: QueryParams) => [...queryKeys.reports.all, 'board-summary', params] as const,
  },
  admin: {
    all: [...appScope, 'admin'] as const,
    users: (params: QueryParams) => [...queryKeys.admin.all, 'users', params] as const,
    usersLists: () => [...queryKeys.admin.all, 'users'] as const,
    usersSummary: () => [...queryKeys.admin.all, 'users-summary'] as const,
    userRoles: () => [...queryKeys.admin.all, 'users-roles'] as const,
    activeBranches: () => [...queryKeys.admin.all, 'active-branches'] as const,
    permissionCatalog: () => [...queryKeys.admin.all, 'permission-catalog'] as const,
    userPermissions: (userId: number) => [...queryKeys.admin.all, 'user-permissions', userId] as const,
    userSecurityState: (userId: number) => [...queryKeys.admin.all, 'user-security-state', userId] as const,
  },
}
